apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeflow-profiles
  namespace: daaas-system
spec:
  project: default
  source:
    repoURL: 'https://github.com/blairdrummond/fake-kubeflow-profiles.git'
    path: profiles
    targetRevision: master
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kubeflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
